import importlib.util
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

spec = importlib.util.spec_from_file_location("llm_judge", ROOT / "llm-judge.py")
llm_judge = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(llm_judge)


class BlindingTest(unittest.TestCase):
    def test_strips_xk6docs_generated_header(self):
        script = (
            "// Generated by k6-create-xk6docs on 2026-05-21T10:48:11.849Z\n"
            "/**\n * QuickPizza gRPC test\n */\n"
            "import { Client } from 'k6/net/grpc';\n"
        )
        blinded = llm_judge._strip_skill_identity(script)
        self.assertNotIn("Generated by", blinded)
        self.assertNotIn("k6-create-xk6docs", blinded)
        # Real content is preserved.
        self.assertIn("QuickPizza gRPC test", blinded)
        self.assertIn("import { Client }", blinded)

    def test_strips_grafana_k6_generated_header(self):
        script = (
            "// Generated by grafana-k6 skill on 2026-05-21\n"
            "import http from 'k6/http';\n"
        )
        blinded = llm_judge._strip_skill_identity(script)
        self.assertNotIn("Generated by", blinded)
        self.assertNotIn("grafana-k6", blinded)
        self.assertIn("import http", blinded)

    def test_leaves_mcp_style_scripts_unchanged(self):
        # mcp-k6 produces no skill header, so the script should be untouched.
        script = (
            "import http from 'k6/http';\n"
            "import { check, sleep } from 'k6';\n"
            "\n"
            "export const options = { vus: 5, duration: '30s' };\n"
        )
        blinded = llm_judge._strip_skill_identity(script)
        self.assertEqual(blinded.strip(), script.strip())

    def test_blinding_does_not_remove_unrelated_comments(self):
        script = (
            "// Generated by k6-create-xk6docs on 2026-05-21T11:00:00.000Z\n"
            "/**\n"
            " * Generated values are derived from __VU and Date.now().\n"
            " * Section dividers below.\n"
            " */\n"
            "// ── HTTP requests ─────────────────────────────────────\n"
            "import http from 'k6/http';\n"
        )
        blinded = llm_judge._strip_skill_identity(script)
        # The literal "Generated by" line is gone.
        self.assertNotIn("Generated by k6-create-xk6docs", blinded)
        # Unrelated comments that happen to use the word "Generated" survive.
        self.assertIn("Generated values are derived from", blinded)
        self.assertIn("HTTP requests", blinded)


if __name__ == "__main__":
    unittest.main()
