// Generated by k6-create-xk6docs on {{GENERATED_AT}}
/**
 * k6 browser example — k6/browser with expect() assertions
 *
 * Covers: browser.newPage(), goto(), getBy* APIs, locator(),
 *         expect() retrying assertions, try/finally page.close(),
 *         shared-iterations scenario with browser options
 *
 * ELEMENT SELECTION — use getBy* APIs as the first choice:
 *   page.getByRole('button', { name: 'Submit' })  ← preferred for interactive elements
 *   page.getByLabel('Username')                    ← preferred for labelled inputs
 *   page.getByText('Rated!')                       ← preferred for text content
 *   page.getByTestId('pizza-btn')                  ← preferred when data-testid exists
 *   page.getByPlaceholder('Enter email')           ← preferred for placeholder inputs
 *   page.locator('#id')                            ← fallback: stable ID attribute
 *   page.locator('button').first()                 ← last resort only — no context
 *
 * ASSERTIONS — use expect() from k6-testing, NOT check() from k6:
 *   expect() on browser locators auto-retries until timeout, replacing the
 *   verbose waitFor() + isVisible() + check() pattern.
 *   Retrying matchers: toBeVisible, toBeHidden, toBeEnabled, toBeChecked,
 *     toHaveText, toContainText, toHaveAttribute, toHaveValue, toHaveTitle
 *
 *   If you need metric-tracked check() in an async browser function, import
 *   the async-compatible version: import { check } from 'https://jslib.k6.io/k6-utils/1.5.0/index.js'
 *   The standard check from 'k6' does NOT work in async contexts.
 *
 * LOCATOR ACTIONABILITY — locators have built-in waits:
 *   - Do NOT call waitFor() before interacting (click, fill, etc.)
 *   - Do NOT use waitForLoadState() after navigation or clicks
 *   - Just interact with the next element you expect — locators wait automatically
 *
 * IMPORTANT:
 * - Default function MUST be async
 * - Do NOT use --vus or --iterations CLI flags — options.scenarios controls load
 * - browser options go inside the scenario, not at the top level
 */
import { expect } from 'https://jslib.k6.io/k6-testing/0.6.1/index.js';
import { browser } from 'k6/browser';

export const options = {
  scenarios: {
    default: {
      executor: 'shared-iterations',
      options: {
        browser: { type: 'chromium' },
      },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  try {
    await page.goto('https://quickpizza.grafana.com');
    await page.screenshot({ path: 'screenshots/1-homepage.png' });

    // getBy* locators wait automatically — no waitFor() needed before click()
    await page.getByRole('button', { name: 'Pizza, Please!' }).click();
    await page.screenshot({ path: 'screenshots/2-after-click.png' });

    await page.getByRole('button', { name: 'Love it!' }).click();

    // expect() auto-retries on browser locators — replaces waitFor + isVisible + check
    await expect(page.getByText('Rated!')).toBeVisible();
    await page.screenshot({ path: 'screenshots/3-rated.png' });

    // Other useful retrying assertions:
    // await expect(page).toHaveTitle(/QuickPizza/);
    // await expect(page.locator('#result')).toContainText('Success');
  } finally {
    await page.close();
  }
}
