// Generated by k6-create-xk6docs on {{GENERATED_AT}}
/**
 * k6 browser example — k6/browser
 *
 * Covers: browser.newPage(), goto(), getBy* APIs, locator(), click(),
 *         check(), try/finally page.close(),
 *         shared-iterations scenario with browser options
 *
 * ELEMENT SELECTION — use getBy* APIs as the first choice:
 *   page.getByRole('button', { name: 'Submit' })  ← preferred for interactive elements
 *   page.getByLabel('Username')                    ← preferred for labelled inputs
 *   page.getByText('Rated!')                       ← preferred for text content
 *   page.getByTestId('pizza-btn')                  ← preferred when data-testid exists
 *   page.getByPlaceholder('Enter email')           ← preferred for placeholder inputs
 *   page.locator('#id')                            ← fallback: stable ID attribute
 *   page.locator('[data-test="x"]')               ← fallback: custom data attribute
 *   page.locator('button[type="submit"]')          ← fallback: unambiguous attribute
 *   page.locator('button').first()                 ← last resort only — no context
 *   page.locator('//xpath')                        ← avoid: fragile, hard to read
 *
 * LOCATOR ACTIONABILITY — locator APIs have built-in actionability checks:
 *   - Do NOT call waitFor() before interacting with an element (click, fill, etc.).
 *     The locator will automatically wait for the element to be visible, enabled,
 *     and stable before performing the action.
 *   - Only use waitFor() when you need to wait for an element WITHOUT interacting
 *     with it (e.g. asserting it appears after an async operation).
 *   - Do NOT use waitForLoadState() after navigation or clicks. Instead, interact
 *     directly with the next element you expect to appear — the locator's
 *     actionability checks handle the waiting for you.
 *
 * IMPORTANT:
 * - Default function MUST be async.
 * - Do NOT use --vus or --iterations CLI flags — the options.scenarios block
 *   controls load for browser scripts.
 * - browser options go inside the scenario, not at the top level.
 *
 * BROWSER BEST PRACTICES (look up via k6 x docs before reviewing a script):
 *   $DOCS_CMD using-k6-browser/recommended-practices/select-elements
 *   $DOCS_CMD using-k6-browser/recommended-practices/handle-dynamic-elements
 *   $DOCS_CMD using-k6-browser/recommended-practices/sleep-vs-page-wait-for-timeout
 *   $DOCS_CMD using-k6-browser/recommended-practices/clean-up-test-resources-page-close
 *   $DOCS_CMD using-k6-browser/recommended-practices/prevent-cookie-banners-blocking
 *   $DOCS_CMD using-k6-browser/recommended-practices/prevent-too-many-time-series-error
 *   $DOCS_CMD using-k6-browser/recommended-practices/hybrid-approach-to-performance
 *   $DOCS_CMD using-k6-browser/recommended-practices/page-object-model-pattern
 *   $DOCS_CMD using-k6-browser/recommended-practices/simulate-user-input-delay
 */
import { browser } from 'k6/browser';
import { check } from 'k6';

export const options = {
  scenarios: {
    browser_test: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 1,
      maxDuration: '2m',
      options: {
        browser: { type: 'chromium' },
      },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  try {
    // Navigate to the page — no waitForLoadState needed after goto().
    // Just start interacting with the first element you expect on the page.
    await page.goto('https://quickpizza.grafana.com');

    // ── Interacting with elements ─────────────────────────────────────────────
    // No waitFor() before click() — locators automatically wait for the element
    // to be visible, enabled, and stable before performing the action.
    await page.getByRole('button', { name: 'Pizza, Please!' }).click();

    // No waitForLoadState() after click() — just interact with the next element
    // you expect. If the recommendation card appears asynchronously, the locator
    // will wait for it automatically.
    await page.getByRole('button', { name: 'Love it!' }).click();

    // ── Asserting without interacting ─────────────────────────────────────────
    // waitFor() IS appropriate here: we're asserting an element appears but
    // not clicking/filling it. Use it to confirm async state changes.
    const rated = page.getByText('Rated!');
    await rated.waitFor({ state: 'visible', timeout: 5000 });

    check(await rated.isVisible(), {
      'rated confirmation visible': (v) => v === true,
    });

    // ── Fallback to locator() only when no getBy* applies ────────────────────
    // e.g. stable ID or unambiguous attribute selector:
    // const input = page.locator('#username');
    // await input.fill('myuser');  // no waitFor() needed before fill()

  } finally {
    // Always close the page — even if the test throws
    await page.close();
  }
}
